# Generated by Django 5.2.5 on 2025-08-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_read_by_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
